# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_num', models.IntegerField(unique=True, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0437\u0430\u043f\u0440\u043e\u0441\u0430')),
                ('title', models.CharField(max_length=255, verbose_name='\u0422\u0435\u043c\u0430')),
                ('text', models.TextField(verbose_name='\u041e\u0431\u0440\u0430\u0449\u0435\u043d\u0438\u0435')),
                ('full_name', models.CharField(max_length=255, verbose_name='\u0418\u043c\u044f \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f')),
                ('phone_number', models.CharField(blank=True, max_length=12, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('user_email', models.EmailField(max_length=254, verbose_name='Email \u0430\u0434\u0440\u0435\u0441\u0441')),
                ('status', models.CharField(choices=[('new', '\u041d\u043e\u0432\u043e\u0435 \u043e\u0431\u0440\u0430\u0449\u0435\u043d\u0438\u0435'), ('published', '\u041e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d\u043d\u043e'), ('decline', '\u041e\u0442\u043a\u043b\u043e\u043d\u0435\u043d'), ('duplicate', '\u0414\u0443\u0431\u043b\u0438\u043a\u0430\u0442')], max_length=30, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0442\u0432\u0435\u0442\u0430')),
            ],
        ),
    ]
